Bengkel_1/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bengkel_1.Models
{
    public class Employee
    {
        public Employee()
        {

        }

        [Required]
        public int ID { get; set; }

        [Required]
        [Display(Name ="First Name")]
        public string FName { get; set; }

        [Display(Name = "Last Name")]
        public string LName { get; set; }

        public string Department { get; set; }

        [Required]
        [Phone(ErrorMessage ="Sila masukkan format nombor telefon yang betul")]
        public string PhoneNo { get; set; }

        [EmailAddress(ErrorMessage ="Sila masukkan format email yang betul")]
        public string Email { get; set; }

        public static Employee GetEmployee(int id)
        {
            Employee emp = new Employee
            {
                ID = Convert.ToInt32(id),
                FName = "John",
                LName = "MacGyver",
                Department = "Human Resource",
                PhoneNo = "017-1234567",
                Email = "manjacat@youtube.com",
            };
            return emp;
        }

        public static IEnumerable<Employee> GetEmployees()
        {
            List<Employee> results = new List<Employee>();

            for (int i = 0; i < 10; i++)
            {
                Employee emp = Employee.GetEmployee(i);
                results.Add(emp);
            }

            return results;
        }       
    
    }

}

Bengkel_1/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bengkel_1.Models
{
    public class Student
    {
        public Student()
        {
            
        }

        [Required]
        public int ID { get; set; }

        [Required]
        public string FName { get; set; }
        public string LName { get; set; }

        public static Student GetStudent(int id)
        {
            Student st = new Student
            {
                ID = id,
                FName = "Ahmad",
                LName = "Maslan"
            };

            return st;
        }
    }
}

Bengkel_1/Controllers/EmployeeController.cs
using Bengkel_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bengkel_1.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            IEnumerable<Employee> emps = Employee.GetEmployees();
            return View(emps);
        }

        public ActionResult Details(string id)
        {
            int idNo = Convert.ToInt32(id);
            Employee emp = Employee.GetEmployee(idNo);
            return View(emp);
        }

        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Index");
            }
            int idNo = Convert.ToInt32(id);
            Employee emp = Employee.GetEmployee(idNo);
            return View(emp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Employee emp)
        {
            if (ModelState.IsValid)
            {
                //Save Changes
                ViewBag.Message = string.Format("Edited emp-{0} successfully.", emp.ID);
            }
            return View(emp);
        }
    }
}

Bengkel_1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bengkel_1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Bengkel_1/Controllers/StudentEmployeeController.cs
using Bengkel_1.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bengkel_1.Controllers
{
    public class StudentEmployeeController : Controller
    {
        // GET: StudentEmployee
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Edit(string id, string msg)
        {
            if (!string.IsNullOrEmpty(msg))
            {
                
            }
            int idNo = Convert.ToInt32(id);
            StudentEmployee student = StudentEmployee.GetStudentEmployee(idNo);
            return View(student);
        }

        [HttpPost]
        public ActionResult Edit(StudentEmployee st)
        {
            //ModelState.Remove("Employee.Email");
            if (ModelState.IsValid)
            {
                ViewBag.Message = "No Error";
            }
            return View(st);
        }

    }
}

Bengkel_1/Views/Employee/Details.cshtml
@model Bengkel_1.Models.Employee

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Bengkel_1/Views/Employee/Edit.cshtml
@model Bengkel_1.Models.Employee

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <div>
            <span class="text-success">@ViewBag.Message</span>            
        </div>
        <hr />
        <div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bengkel_1/Views/Employee/Index.cshtml
@model IEnumerable<Bengkel_1.Models.Employee>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>Action</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Bengkel_1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Bengkel_1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Bengkel_1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Bengkel_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Employee", "Index", "Employee")</li>
                    <li>@Html.ActionLink("ViewModel Test", "Edit", "StudentEmployee", new { id = 5}, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Bengkel_1/Views/StudentEmployee/Edit.cshtml
@model Bengkel_1.ViewModel.StudentEmployee

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div>
            <span class="text-primary">@ViewBag.Message</span>
        </div>
        <h4>StudentEmployee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <hr />
        <div>
            <div>
                <span class="modal-title">ini Employee Model</span>
                @Html.HiddenFor(x => x.Employee.ID)
            </div>
            <div class="form-group">
                <span class="control-label col-md-2">First Name</span>
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Employee.FName)
                    @Html.ValidationMessageFor(x => x.Employee.FName)
                </div>
            </div>
            <div class="form-group">
                <span class="control-label col-md-2">Last Name</span>
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Employee.LName)
                    @Html.ValidationMessageFor(x => x.Employee.LName)
                </div>
            </div>
            <div class="form-group">
                <span class="control-label col-md-2">Email</span>
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Employee.Email)
                    @Html.ValidationMessageFor(x => x.Employee.Email)
                </div>
            </div>
            <div class="form-group">
                <span class="control-label col-md-2">Phone No</span>
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Employee.PhoneNo)
                    @Html.ValidationMessageFor(x => x.Employee.PhoneNo)
                </div>
            </div>
        </div>
        <hr />
        <div>
            <span class="modal-title">Ini Student punya Model</span>
        </div>
        <div>
            @Html.HiddenFor(x => x.Student.ID)
            <div class="form-group">
                <span class="control-label col-md-2">First Name</span>
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Student.FName)
                    @Html.ValidationMessageFor(x => x.Student.FName)
                </div>
            </div>
            <div class="form-group">
                <span class="control-label col-md-2">Last Name</span>
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Student.LName)
                    @Html.ValidationMessageFor(x => x.Student.LName)
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bengkel_1/Views/StudentEmployee/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
